In [18]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np

v = np.zeros(10)

print(v)

print("fifth value is 1")

v[4] = 1

print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
fifth value is 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
#2. Create a vector with values ranging from 10 to 49.
import numpy as np
v = np.arange(10,49)
print(v)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [21]:
#3. Create a 3x3 matrix with values ranging from 0 to 8.
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0].
import numpy as np
x = [1,2,0,0,4,0]
y = np.nonzero(x)
print(y)


(array([0, 1, 4], dtype=int64),)


In [32]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)



Original Array:
[[0.93729631 0.88675523 0.44473296 0.79348982 0.16557418 0.09559923
  0.01083057 0.39530526 0.95174271 0.06861215]
 [0.14840362 0.83050374 0.79755845 0.74925375 0.86650577 0.46095804
  0.64754133 0.08578842 0.03663802 0.88295022]
 [0.29751384 0.37978917 0.88012255 0.07073901 0.01520878 0.40349932
  0.37517086 0.49849009 0.02538424 0.49375539]
 [0.37301626 0.09155996 0.03874171 0.29417592 0.07884513 0.06764412
  0.10287208 0.14929246 0.99162905 0.68352434]
 [0.22202885 0.74485634 0.03916395 0.10523836 0.2591338  0.88255828
  0.4067901  0.96145554 0.34844637 0.66293157]
 [0.705025   0.3641453  0.65589254 0.71542479 0.59229576 0.49617961
  0.20661332 0.71530974 0.38745015 0.38500355]
 [0.17668461 0.42365008 0.21237628 0.48300981 0.39132534 0.9935704
  0.26216375 0.54830827 0.54320184 0.73933976]
 [0.72965096 0.93069957 0.39590892 0.09777409 0.12278346 0.14020691
  0.51890954 0.48222614 0.76242662 0.63083884]
 [0.14268503 0.32521718 0.81317409 0.40973089 0.76837716 0.650722

In [38]:
#6. Create a random vector of size 30 and find the mean value.
a = np.random.random(30)
print(a)
print("mean value:")
b = a.mean()
print(b)

[0.08139035 0.71027486 0.18552188 0.03139806 0.77434538 0.89488557
 0.34348512 0.41503427 0.27687888 0.52342375 0.2423119  0.78538532
 0.90374477 0.85327112 0.2817541  0.66424656 0.71705856 0.53359167
 0.61532601 0.37562304 0.70490448 0.74386157 0.1094951  0.28877009
 0.92947307 0.81220294 0.63137395 0.91716757 0.83609346 0.97097424]
mean value:
0.5717755880053969
